// Syntax error
// var x=0,y=0;

// try{
// 	LABEL1 : do {
//         x++;
//         eval("continue LABEL1");
//         y++;
//     } while(0);
// 	$ERROR('#1: eval("continue LABEL1") does not lead to throwing exception');
// } catch(e){
// 	if(!(e instanceof SyntaxError)){
// 		$ERROR("1.1: Appearing of continue within eval statement inside of IterationStatement yields SyntaxError");
// 	}
// }
