  try
{    if (Function.prototype(x) !== undefined)
    {
      var x;
      $ERROR('#1: The Function prototype object is itself a Function object that, when invoked, accepts any arguments and returns undefined');
    }}
  catch (e)
{    $ERROR('#1.1: The Function prototype object is itself a Function object that, when invoked, accepts any arguments and returns undefined: ' + e);}

  